# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59f622b7645a4ee7d1994dd3c3f98248c35ed03564bdc8e9032b4a6d0473baa536c43a3895fb92571db6bf0b5c0a5ee4cc37b1e638c5d69d21b510e8ca83d3b3

test:
  secret_key_base: 53b078fa2c6347dac4c002b40ef87b5556c7d0abba88d2afede1c6fcc7eb2d6aa3c721d67cc35a3f7176928eb71b2da8e0230be9cf3afc34fec7e80688e6f1d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
